### ISSUE TITLE
Unable to import the training workspace

### ISSUE THREAD

**Issue by RemyLespagnol** [watson-developer-cloud/car-dashboard#10]
When we import the training dataset to the conversation service, we have this error : 

`Unable to import workspace from file car_dashboard.json. Error: column "go_to" of relation "node" does not exist`

But if we import only entities and intents, it's works.

So the dialog can't be imported.

**Comment by doconnor78** [comment]
Hello.. It is likely you were trying to import the latest workspace into a experimental version of the service? go_tos were not supported in experimental, so its most likely that this is the issue. Please re-test with a 'standard' or 'free' version of the service. Please re-open if that is not the case.
