### ISSUE TITLE
Service really down ?

### ISSUE THREAD

**Issue by gitjps** [watson-developer-cloud/car-dashboard#11]
Error right deployment to Bluemix:

The service may be down at the moment; please check here for the current status.
If the service is OK, the app may not be configured correctly, please check workspace id and credentials for typos.
If the service is running and the app is configured correctly, try refreshing the page and/or trying a different request.

[Status](https://status.ng.bluemix.net/) of conversation service is green, though.

**Comment by doconnor78** [comment]
@ColbyJohnIBM Could you take a look at integrating better error handling.. Basically when we get an error from the service (https://github.com/watson-developer-cloud/car-dashboard/blob/master/app.js#L90) perhaps send a message back that the client can use.. `401 = The credentials you are using don't appear to be correct` etc..

**Comment by gitjps** [comment]
I didn't recognize that another conversation service was created, so I changed the workspace id. thx
