### ISSUE TITLE
"Turning off the radio" not represented in UI

### ISSUE THREAD

**Issue by eightBEC** [watson-developer-cloud/car-dashboard#37]
When the music is turned on, it's reflected in the UI. 
When I issue the command "Turn the radio off" nothing action is taken, that is visible to the user.

![turnoff](https://cloud.githubusercontent.com/assets/16187615/18390043/ef15de74-76a8-11e6-8e68-06851165d872.PNG)

**Comment by germanattanasio** [comment]
The radio will be off once the song finish. Do you really want to stop the Jazz song?
