### ISSUE TITLE
How can I changes the Images

### ISSUE THREAD

**Issue by adolfoalamo** [watson-developer-cloud/car-dashboard#38]
Hi,
I am trying to changes the images to make the car to look like an airplane dashboard but when I unloaded the new images using the same name and of originals and I build and deploy the new image does not show on the app, still show the old car dashboard instead of my new airplane dashboard.  Please advice.  Thank you

**Comment by germanattanasio** [comment]
The images are part of the style so you need to not only change them in the code but also run gulp to compile them.
