### ISSUE TITLE
Make API calls and give the data back to Watson

### ISSUE THREAD

**Issue by the-dagger** [watson-developer-cloud/car-dashboard#39]
Hey all, 
Is there a way in which I can get the data entered by the user (e.g. the city name) and use it for making an API call and return the response back to Watson?
I tried looking through the code but couldn't find a way to do it.
Any help would be appreciated.
Cheers.

**Comment by germanattanasio** [comment]
Take a look at this example http://text-bot.mybluemix.net.
Code: https://github.com/watson-developer-cloud/text-bot

It uses IBM Watson Conversation and AlchemyLanguage. The README should give you the information you are looking for
