### ISSUE TITLE
App not showing conversation after successful deployment

### ISSUE THREAD

**Issue by sourabhks** [watson-developer-cloud/car-dashboard#44]
Once the app is deployed, it does not show conversation. The services may be down error is thrown. Kindly help

**Comment by dgterry** [comment]
Hello,
Could you please let us know if you are deploying the application to bluemix or if you are setting up in a local development environment?

Once it is deployed do you see a message like this:

> The service may be down at the moment; please check here for the current status. 
> If the service is OK, the app may not be configured correctly, please check workspace id and credentials for typos. 
> If the service is running and the app is configured correctly, try refreshing the page and/or trying a different request.

If so, you likely need to import the workspace json into your conversation service and then tell the app what the workspace id is by setting it in the WORKSPACE_ID environment variable.  These instructions should help: https://github.com/watson-developer-cloud/car-dashboard#workspace

**Comment by sourabhks** [comment]
I am deploying application to bluemix and yes its showing the same message which you wrote like " The service may be down at the moment"
Please help as I have deployed the application to bluemix multiple times in different regions but nothing has helped till now.  And I have added WORKSPACE_ID of conversation service in the app

**Comment by ashleylord8** [comment]
Hi @sourabhks,

Are you still getting this issue? If you are I think I may know what the problem and solution are. 

I was walking through the steps to deploy to Bluemix in the car-dashboard repo https://github.com/watson-developer-cloud/car-dashboard and noticed that the **"Adding environment variables in Bluemix"** section was not up to date. This is crucial to make the show the desired conversation. 

For the time being, I am going to point you to our conversation-enhanced repo  https://github.com/watson-developer-cloud/conversation-enhanced and ask you to follow the steps under **"Adding environment variables in Bluemix"** section in there. This worked for me and I hope it helps you!
