### ISSUE TITLE
Pop up chatbot proactively

### ISSUE THREAD

**Issue by sourabhks** [watson-developer-cloud/car-dashboard#52]
Hi, 
Can we make the app popup proactively based on change in table(database).
For ex. after starting the app locally, it starts reading the table column and 
when finds a change in table column, the chatbot starts itself to interact with
the user.
Please give me some reference or guide as how to go about it. Thanks

**Comment by mitchmason** [comment]
Hi, I dont think I understand your use case, and I know that we don't have any sample code that does that already. Using watson conversation is based on making an API call, so your client side code would check the db, and when appropriate make the call to the watson service.
