### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by viniciusdepaula** [watson-developer-cloud/car-dashboard#53]
When the payload is posted in endpoint /api/message:

{"input":{"text":"hi"}}

The follow response is returned (500 Internal Server Error):

{"code":500,"error":"Resource not found"}

**Comment by mitchmason** [comment]
This likely means your credentials or workspace_id are incorrect

**Comment by anthonyshay** [comment]
For anyone that is wondering where they can find the credentials, here's how:

1- Log in to Bluemix.
2- Select Catalog and then Watson to get to the list of services
3- Select a service, and then create an instance of the service by clicking Create.
4- Select Service Credentials and then View Credentials on the service dashboard.
