### ISSUE TITLE
Speech To Text error

### ISSUE THREAD

**Issue by athifashaffy** [watson-developer-cloud/car-dashboard#56]
The STT service doesn't work in the application , while debugging the following error is resulted-"Uncaught TypeError: Cannot read property 'callRetrieveAndRank' of undefined "

**Comment by stevenpkg** [comment]
This has been fixed now

**Comment by AlaGarali** [comment]
I found these errors :

1) speech-to-text.js:47 Uncaught TypeError: Api.setWatsonPayload is not a function
    at Object.micON (speech-to-text.js:47) ==> Api.setWatsonPayload({output: {text: ['Accept the microphone prompt in your browser. Watson will listen soon.'], ref: 'STT'}}); 
    at HTMLDivElement.onclick ((index):42)

2) text-to-speech.js:23 Uncaught TypeError: Cannot set property 'value' of null
    at text-to-speech.js:23 ==> (button.value = 'ON';)
    at text-to-speech.js:109

Can you help me please ??

**Comment by stevenpkg** [comment]
@AlaGarali I will take a look at this

**Comment by AlaGarali** [comment]
Dear Sir Steven,

Please, find attached my first chatbot project. Please take a look in order to resolve the error and run both STT and TTS services.

The attached .zip file is missing the node_modules folder because it is large (96,6 Mo).

Thank you very much.

[Chatbot.zip](https://github.com/watson-developer-cloud/car-dashboard/files/2168463/Chatbot.zip)

**Comment by stevenpkg** [comment]
@AlaGarali There are numerous errors in your code, I fixed a few, but there are too meany errors for me to fix ATM. Please be careful with renaming, you need to change setWatsonPayload to setResponsePayload in api.js. If you use Firefox or Chrome open developer mode and you will see the errors on the client side, here are some:

![screen shot 2018-07-06 at 10 30 03 am](https://user-images.githubusercontent.com/23624214/42354064-958dedae-8107-11e8-8e5d-2fdc13a247ab.png)

**Comment by AlaGarali** [comment]
I renamed setWatsonPayload to setResponsePayload and that error is fixed.
What are the others errors that your have fixed yesterday ?
Please find attached the errors on the client side (Chrome developer mode).
Thanks.


![image](https://user-images.githubusercontent.com/30980622/42370378-835df366-8104-11e8-8984-3d11fc32bc80.png)

**Comment by AlaGarali** [comment]
Dear @stevenpkg,
I'm trying to build Customer Support Agent with IBM Watson Conversation, STT, TTS and Discovery Services and uploading FAQs documents (.docx, .pdf, .html) to Discovery service.

I would like to know, how can I have the right answer of a question asked, from documents (html, docx, pdf, ...) uploaded on discovery service ? How can I configure discovery service or discovery.query(){} (code below) to return the best answer of user's question ? Should I use another service such as WKS or not ? Please find below my discovery.js file code:

  function sendToDiscovery(query) {
  return new Promise(function(resolve, reject) {
    var DiscoveryV1 = require('watson-developer-cloud/discovery/v1');

    var discovery = new DiscoveryV1({
      username: process.env.DISCOVERY_USERNAME,
      password: process.env.DISCOVERY_PASSWORD,
      version_date: '2018-03-05'
    });

    var environment_id = process.env.ENVIRONMENT_ID;
    var collection_id = process.env.COLLECTION_ID;
    var params = {query: query,
        //natural_language_query: query
        //filter: score>0.8,
        highlight: true,
        passages_count: 1,
        passages: true,
        return_fields: ['text'],
        count:1,
        return: 'text'
        //aggregation:
        //'[term(enriched_text.entities.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.categories.label).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.concepts.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.keywords.text).term(enriched_text.sentiment.document.label),' +
        //'term(enriched_text.entities.type).term(enriched_text.sentiment.document.label)]'
    }
    discovery.query({
      environment_id: environment_id,
      collection_id: collection_id,
      configuration_id: process.env.DISCOVERY_CONFIGURATION_ID,
      query : params
    }, function(error, response) {
        if (error) {
          reject(error);
        } else {
          if (response.results == null) {
            console.log("The call to the Discovery service is complete, but he has not returned any replies. Check the format of the data injected into the Discovery service.");
            reject(error);
          } else {
            console.log(response.results[0].text);
            resolve(response.results[0].text);
          }
        }
    });
  });
}
module.exports = sendToDiscovery;

Could you help me please ?

Best regards.

**Comment by stevenpkg** [comment]
@AlaGarali I am sorry but we do not support debugging customers own projects. I recommend going back to the assistant with discovery code, and make changes slowly, testing each step of the way to make sure nothing gets broken.
