### ISSUE TITLE
Update to latest watson-speech library

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/car-dashboard#57]
The version included here doesn't support customizations or a few other newer features; we should update it to the latest. However, there was one [breaking change](https://www.npmjs.com/package/watson-speech#breaking-change-for-v0220) that means the [data handling](https://github.com/watson-developer-cloud/car-dashboard/blob/630839844ce0fd9452fe9cd88c4f11220f2681ee/ui/ibm/speech-to-text.js#L82) will need to be tweaked.

Ideally it should also come from npm or bower so that upgrades could be more easily tracked, and perhaps use webpack or similar to bundle all of the scripts together into one, but that may be a separate task.

**Comment by stevenpkg** [comment]
@nfriedly is this still something you thing is worth doing?

**Comment by nfriedly** [comment]
Yea, I think so.
