### ISSUE TITLE
Fails to Deploy in Bluemix

### ISSUE THREAD

**Issue by gyleodhis** [watson-developer-cloud/car-dashboard#62]
When cloning this project to bluemix, everything works fine but only upto "configured pipeline successfully" but fails to deploy to bluemix what could be the issue.

**Comment by prateekroopra** [comment]
Same problem!

**Comment by germanattanasio** [comment]
@stevenpkg ^^

**Comment by stevenpkg** [comment]
Can you give me more detail, commands you're using, any error given
