### ISSUE TITLE
Unable to import workspace from file car_workspace.json

### ISSUE THREAD

**Issue by leandrodvd** [watson-developer-cloud/car-dashboard#73]
I'm trying to import the car workspace but I get the following error:

_Unable to import workspace from file car_workspace.json. Error: {"error":{"intents":[{"examples":[{"text":["text can not contain the following characters: tab, new line, carriage return, slashes."]}]},{"examples":[{"text":["text can not contain the following characters: tab, new line, carriage return, slashes...._

The same happens if I try to edit the "Car Dashboard - Sample" that is provided within the service and is available in the list of  workspaces

Not sure if this is relevant but I already have 2 workspaces created.

**Comment by ttlew** [comment]
Yes this is a known error that we are addressing. @doconnor78 will you be able to update this workspace as well?

**Comment by leandrodvd** [comment]
Is there any easy workaround ?

**Comment by doconnor78** [comment]
@leandrodvd There is an easy workaround, just search through the json and remove `/` and `\` from the intent and entity training data. Please take a look at my pr:
https://github.com/watson-developer-cloud/car-dashboard/pull/74
It has an updated workspace with the fixes in place, feel free to copy that workspace instead:
https://raw.githubusercontent.com/watson-developer-cloud/car-dashboard/ad38bf588fda8041e22eced32d6166ddc5024715/training/car_workspace.json

@ttlew I've already put in a PR for this repo, awaiting access to the other repos to replicate the fix.

**Comment by germanattanasio** [comment]
Fixed by @doconnor78
