### ISSUE TITLE
Speech input gets a timeout error

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/car-dashboard#77]
The speech input depends on the `continuous: false` behavior that was [removed from the API in may](https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html#May2017).

The SDK has [an example](https://watson-speech.mybluemix.net/microphone-streaming-auto-stop.html) of how to achieve the same behavior now, but since this is apparently breaking live applications, I'm going to see if I can put a workaround in the SDK to automatically implement the old behavior when `continuous: false` is set.

But, either way, this app will require an update - either to implement the workaround or else to update to the latest SDK.

**Comment by stevenpkg** [comment]
will take a look

**Comment by germanattanasio** [comment]
did we update the

**Comment by germanattanasio** [comment]
Why did you close the issue @stevenpkg? I think we need to update the sample to use the latest version of the speech-min.js package.

**Comment by stevenpkg** [comment]
@germanattanasio I just closed as this was opened 6 month ago. Yes I can update speech-min.js

**Comment by stevenpkg** [comment]
I intend to update speech-min in the next week or so
