### ISSUE TITLE
error after deploying to BM :  "Cannot GET /"

### ISSUE THREAD

**Issue by gitjps** [watson-developer-cloud/car-dashboard#8]
I couldn't find:

 app.get ( '/', auth, function (req, res) {
 only 

app.get ( '/chats', auth, function (req, res) {
Logs:

App/0scripts/start: line 60: 398 Killed ${NODE_EXECUTABLE} ${NODE_OPTS} ${BOOT_SCRIPT} ${NODE_ARGS}2016-07-27T05:52:30.194+0200
App/0Debugger listening on port 58582016-07-27T05:52:31.628+0200
App: https://car-dashboard-jps-2218.mybluemix.net/

**Comment by JeevithaSelvaraj** [comment]
I have the same issue too.Kindly help with the same.

**Comment by Sud-Puth** [comment]
Hi @Peter99084 , @JeevithaSelvaraj , Please redeploy the application with the latest code, the issue should be fixed and you should be able to access the application.
Please re-open if that is not the case.
