### ISSUE TITLE
Deploying to IBM Cloud creates incorrect credentials

### ISSUE THREAD

**Issue by thinkscientist** [watson-developer-cloud/car-dashboard#90]
When I try to deploy the application to IBM cloud.

I get it to deploy succesfully. Even though the car JSON doesn't import into Watson assistant the car dashboard exists as a sample workspace so I have imported that.

However the services that it automatically provisions, text to speech, speech to text etc don't match!

I get error messages in the logs around the user name and password being wrong. When i check the VCAP_SERVICES environment variables they don't match what exists in the services that are provisioned but i have no way of changing them to the accurate ones.

I have added environment variables for the values to try to override the username and passwords for the service credentials but it hasn't made any difference.

**Comment by germanattanasio** [comment]
Hey @stevenpkg can you take a look at this?

**Comment by stevenpkg** [comment]
@germanattanasio will look into this

@thinkscientist how are you deploying this demo to IBM cloud?

**Comment by Oliver-I** [comment]
@thinkscientist Are you still experiencing this issue?

**Comment by Oliver-I** [comment]
@thinkscientist This will now be closed, if you are still experiencing the issue please re-open and provide the information requested by @stevenpkg .
